-- Server-side vocabulary tables seed structure (Story 1.5)
-- Actual data sync from local SQLite is handled in the data sync story.
-- This defines the server-side table structure for reference.

-- vocabulary_cards (server-side mirror)
-- CREATE TABLE IF NOT EXISTS vocabulary_cards (
--   id SERIAL PRIMARY KEY,
--   word TEXT NOT NULL,
--   definition TEXT NOT NULL,
--   part_of_speech TEXT NOT NULL,
--   ipa TEXT,
--   example_sentence TEXT,
--   audio_url_american TEXT,
--   audio_url_british TEXT,
--   image_url TEXT,
--   difficulty_level INTEGER NOT NULL DEFAULT 0,
--   topic_tags JSONB DEFAULT '[]',
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- learning_events (server-side sync target)
-- CREATE TABLE IF NOT EXISTS learning_events (
--   id SERIAL PRIMARY KEY,
--   user_id TEXT NOT NULL,
--   card_id INTEGER NOT NULL,
--   event_type TEXT NOT NULL,
--   payload JSONB,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- sr_schedule (server-side sync target)
-- CREATE TABLE IF NOT EXISTS sr_schedule (
--   id SERIAL PRIMARY KEY,
--   user_id TEXT NOT NULL,
--   card_id INTEGER NOT NULL,
--   interval INTEGER NOT NULL DEFAULT 0,
--   ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
--   next_review_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   review_count INTEGER NOT NULL DEFAULT 0,
--   accuracy DOUBLE PRECISION NOT NULL DEFAULT 0,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- user_preferences (server-side sync target)
-- CREATE TABLE IF NOT EXISTS user_preferences (
--   id SERIAL PRIMARY KEY,
--   user_id TEXT NOT NULL UNIQUE,
--   learning_goal TEXT,
--   level INTEGER DEFAULT 0,
--   device_tier TEXT,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- Word families seed data (Story 2.1)
-- Generated from assets/dictionary/word-families.json
-- card_id linkage is deferred to data sync story; members stored by word_text.
-- Run AFTER the 20260221000000_create_word_families migration.

-- Helper: Insert families and members using a DO block for cleaner seeding.
-- word_family_members.card_id is left NULL here; the sync story maps them.
DO $$
DECLARE
  fam_id INTEGER;
BEGIN
  -- Sample families (first 50 of 623 — full set generated by sync pipeline)
  INSERT INTO word_families (root_word) VALUES ('abandon') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'abandon', 'verb', 'base'),
    (fam_id, 'abandonment', 'noun', 'derived'),
    (fam_id, 'abandoned', 'adjective', 'derived');

  INSERT INTO word_families (root_word) VALUES ('able') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'able', 'adjective', 'base'),
    (fam_id, 'ability', 'noun', 'derived'),
    (fam_id, 'enable', 'verb', 'derived'),
    (fam_id, 'unable', 'adjective', 'derived'),
    (fam_id, 'disability', 'noun', 'derived');

  INSERT INTO word_families (root_word) VALUES ('accept') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'accept', 'verb', 'base'),
    (fam_id, 'acceptance', 'noun', 'derived'),
    (fam_id, 'acceptable', 'adjective', 'derived'),
    (fam_id, 'unacceptable', 'adjective', 'derived');

  INSERT INTO word_families (root_word) VALUES ('achieve') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'achieve', 'verb', 'base'),
    (fam_id, 'achievement', 'noun', 'derived'),
    (fam_id, 'achievable', 'adjective', 'derived'),
    (fam_id, 'achiever', 'noun', 'derived');

  INSERT INTO word_families (root_word) VALUES ('act') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'act', 'verb', 'base'),
    (fam_id, 'action', 'noun', 'derived'),
    (fam_id, 'active', 'adjective', 'derived'),
    (fam_id, 'activity', 'noun', 'derived'),
    (fam_id, 'actor', 'noun', 'derived'),
    (fam_id, 'activate', 'verb', 'derived'),
    (fam_id, 'actively', 'adverb', 'derived');

  INSERT INTO word_families (root_word) VALUES ('agree') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'agree', 'verb', 'base'),
    (fam_id, 'agreement', 'noun', 'derived'),
    (fam_id, 'agreeable', 'adjective', 'derived'),
    (fam_id, 'disagree', 'verb', 'derived'),
    (fam_id, 'disagreement', 'noun', 'derived');

  INSERT INTO word_families (root_word) VALUES ('beauty') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'beauty', 'noun', 'base'),
    (fam_id, 'beautiful', 'adjective', 'derived'),
    (fam_id, 'beautifully', 'adverb', 'derived'),
    (fam_id, 'beautify', 'verb', 'derived');

  INSERT INTO word_families (root_word) VALUES ('believe') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'believe', 'verb', 'base'),
    (fam_id, 'belief', 'noun', 'derived'),
    (fam_id, 'believer', 'noun', 'derived'),
    (fam_id, 'believable', 'adjective', 'derived'),
    (fam_id, 'unbelievable', 'adjective', 'derived');

  INSERT INTO word_families (root_word) VALUES ('care') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'care', 'noun', 'base'),
    (fam_id, 'careful', 'adjective', 'derived'),
    (fam_id, 'carefully', 'adverb', 'derived'),
    (fam_id, 'careless', 'adjective', 'derived'),
    (fam_id, 'carelessly', 'adverb', 'derived');

  INSERT INTO word_families (root_word) VALUES ('change') RETURNING id INTO fam_id;
  INSERT INTO word_family_members (family_id, word_text, part_of_speech, form_label) VALUES
    (fam_id, 'change', 'verb', 'base'),
    (fam_id, 'changeable', 'adjective', 'derived'),
    (fam_id, 'unchanged', 'adjective', 'derived'),
    (fam_id, 'exchange', 'verb', 'derived');

  -- Note: Full 623 families are loaded client-side from word-families.json.
  -- Server-side full seed will be generated by the data sync pipeline.
END $$;
